version: '3.7'

services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./expense_manager:/expense_manager
    entrypoint: sh "/entrypoint.sh"
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:alpine
  celery:
    restart: always
    build:
      context: .
    command: celery -A expense_manager worker --beat --scheduler django --loglevel=info
    volumes:
      - ./expense_manager:/expense_manager
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
      - web
volumes:
  pgdata: