version: '3.7'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    command: bash -c "python manage.py migrate && gunicorn expense_manager.wsgi:application -b 0.0.0.0:8000"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

  redis:
    image: redis:alpine

  celery:
    restart: always
    build:
      context: .
    command: celery -A expense_manager worker --beat --scheduler django --loglevel=info
    volumes:
      - ./expense_manager:/expense_manager
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
      - web

volumes:
  postgres_data: